### ISSUE TITLE
concentrator - node bootstrap - front

### ISSUE THREAD

**Issue by emanuelcima** [dsec-thesis/concentrator#2]

**Comment by diegosarina** [comment]
Datos:

- nombre de la red
- canal rx y tx lora
- id concentrador
- sf
-

**Comment by emanuelcima** [comment]
- LoraAntennaConfig(BaseModel):
  - frequency: int
  - spreading_factor: int
  - bandwidth: int
  - coding_rate: int
  - preamble_length: int
  - crc_enable: bool
  - sync_word: int


- LoraConfig
  - rx: LoraAntennaConfig
  - tx: LoraAntennaConfig


- ClientConfig
  - client_id: str
  - client_secret: str
  - token_url: str
  - token_file: str
  - api_url: str
  - parkinglot_id: str

- WifiConfig

**Comment by emanuelcima** [comment]
```json
{
    "lora": {
        "rx": {
            "frequency": 916800000,
            "spreading_factor": 7,
            "bandwidth": 125000,
            "coding_rate": 5,
            "preamble_length": 12,
            "crc_enable": true,
            "sync_word": 39
        },
        "tx": {
            "frequency": 867900000,
            "spreading_factor": 7,
            "bandwidth": 125000,
            "coding_rate": 5,
            "preamble_length": 12,
            "crc_enable": true,
            "sync_word": 39
        },
        "spi": {
            "bus": 0,
            "chip_select": 0,
            "reset": 22
        }
    },
    "client": {
        "client_id": "1da561cvkjo4r78975q3n32khh",
        "client_secret": "cg01v4d1g9hqhudomv2smgenestu9i3eosc99o0gtnk79gf2h68",
        "token_url": "https://smartparking-dev.auth.us-east-1.amazoncognito.com/oauth2/token",
        "token_file": "token.json",
        "api_url": "https://vmfj4o7v3m.execute-api.us-east-1.amazonaws.com",
        "parkinglot_id": "4b1343a7-d324-41fa-bd39-6562f150bcad"
    }
}
```

**Comment by diegosarina** [comment]
Fixed

![Screenshot 2023-10-06 at 16 20 04](https://github.com/dsec-thesis/concentrator/assets/50960457/94e354bf-4d5b-4da9-95a8-55796c119b19)
![Screenshot 2023-10-06 at 16 19 59](https://github.com/dsec-thesis/concentrator/assets/50960457/dfb86df4-ab03-48de-910a-9b89ac1c8f88)
![Screenshot 2023-10-06 at 16 19 54](https://github.com/dsec-thesis/concentrator/assets/50960457/a112533a-e860-47a2-9c38-a2c02c434f25)
![Screenshot 2023-10-06 at 16 19 51](https://github.com/dsec-thesis/concentrator/assets/50960457/d2ab806d-6982-4170-8a8a-294c9c72d31b)
![Screenshot 2023-10-06 at 16 19 44](https://github.com/dsec-thesis/concentrator/assets/50960457/12b9758d-a67f-4259-b0a9-294ef740d48c)
